
package com.polisong.view;

import java.awt.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import com.polisong.dao.CancionDAO;
import com.polisong.model.cancion;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */

public class Catalogo extends javax.swing.JFrame {
     private JPanel panelHeader;
    private JLabel titulo;
    private JPanel panelBuscador;
    private JTextField txtBuscar;
    private JButton btnBuscar;
    private JComboBox<String> comboGenero;
    private JScrollPane scrollCatalogo;
    private JPanel panelCatalogo;
    
    
    private JPanel crearCardCancionDB(cancion c) {
    JPanel card = new JPanel(new BorderLayout());
    card.setBackground(Color.WHITE);
    card.setPreferredSize(new Dimension(200, 250));
    card.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200)));

    JLabel lblTitulo = new JLabel(c.getNombre(), SwingConstants.CENTER);
    lblTitulo.setFont(new Font("Arial", Font.BOLD, 16));

    JLabel lblArtista = new JLabel(c.getArtista(), SwingConstants.CENTER);
    lblArtista.setFont(new Font("Arial", Font.PLAIN, 14));

    JPanel info = new JPanel(new GridLayout(2, 1));
    info.add(lblTitulo);
    info.add(lblArtista);

    JButton verBtn = new JButton("Ver detalle");
    verBtn.setBackground(new Color(225, 6, 0));
    verBtn.setForeground(Color.WHITE);

    // Acción para abrir detalle
    verBtn.addActionListener(e -> {
        VerDetalleCancion ventana = new VerDetalleCancion();
        ventana.setVisible(true);
        ventana.cargarCancionPorId(c.getIdCancion());
    });

    card.add(info, BorderLayout.CENTER);
    card.add(verBtn, BorderLayout.SOUTH);

    return card;
}
    
    

    /**
     * Creates new form Catalogo
     */
    public Catalogo() {
        initComponents();
        construirCatalogo();
        cargarCatalogoBD();
    }
    private void construirCatalogo() {

    // ---- CONFIG PANEL BASE ----
    jPanelBase.setLayout(new BorderLayout());

    // ------------------ HEADER ------------------
    panelHeader = new JPanel();
    panelHeader.setBackground(new Color(51, 51, 51));
    panelHeader.setPreferredSize(new Dimension(900, 70));

    titulo = new JLabel("POLISONG STOCK");
    titulo.setFont(new Font("Arial Black", Font.BOLD, 26));
    titulo.setForeground(Color.WHITE);
    panelHeader.add(titulo);

    jPanelBase.add(panelHeader, BorderLayout.NORTH);

    // ------------------ BUSCADOR ------------------
    panelBuscador = new JPanel(new FlowLayout(FlowLayout.LEFT, 20, 20));
    panelBuscador.setBackground(Color.WHITE);

    panelBuscador.add(new JLabel("Buscar canción:"));

    txtBuscar = new JTextField(25);
    panelBuscador.add(txtBuscar);

    btnBuscar = new JButton("Buscar");
    btnBuscar.setBackground(new Color(225, 6, 0));
    btnBuscar.setForeground(Color.WHITE);
    panelBuscador.add(btnBuscar);
    btnBuscar.addActionListener(e -> filtrarPorNombre());

    panelBuscador.add(new JLabel("Género:"));

    comboGenero = new JComboBox<>(new String[]{
        "Todos", "Rock", "Pop", "Jazz", "Salsa", "Reggaeton", "Vallenato"
    });
    panelBuscador.add(comboGenero);
    comboGenero.addActionListener(e -> filtrarPorGenero());

    jPanelBase.add(panelBuscador, BorderLayout.CENTER);

    // ------------------ CATALOGO ------------------
    panelCatalogo = new JPanel();
    panelCatalogo.setLayout(new GridLayout(0, 3, 15, 15));
    panelCatalogo.setBackground(Color.WHITE);
    panelCatalogo.setBorder(new EmptyBorder(20, 20, 20, 20));

    for (int i = 1; i <= 6; i++) {
        panelCatalogo.add(crearCardCancion("Canción " + i, "Artista " + i));
    }

    scrollCatalogo = new JScrollPane(panelCatalogo);
    scrollCatalogo.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

    jPanelBase.add(scrollCatalogo, BorderLayout.SOUTH);
}
    
    private void cargarCatalogoBD() {
    panelCatalogo.removeAll(); // limpia cards

    CancionDAO dao = new CancionDAO();
    List<cancion> lista = dao.visualizarCatalogo();

    for (cancion c : lista) {
        panelCatalogo.add(crearCardCancionDB(c));
    }

    panelCatalogo.revalidate();
    panelCatalogo.repaint();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBase.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private JPanel crearCardCancion(String nombre, String artista) {
        JPanel card = new JPanel();
        card.setLayout(new BorderLayout());
        card.setBackground(Color.WHITE);
        card.setPreferredSize(new Dimension(200, 250));
        card.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200)));

        JLabel lblTitulo = new JLabel(nombre, SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 16));

        JLabel lblArtista = new JLabel(artista, SwingConstants.CENTER);
        lblArtista.setFont(new Font("Arial", Font.PLAIN, 14));

        JPanel info = new JPanel(new GridLayout(2, 1));
        info.add(lblTitulo);
        info.add(lblArtista);

        JButton verBtn = new JButton("Ver detalle");
        verBtn.setBackground(new Color(225, 6, 0));
        verBtn.setForeground(Color.WHITE);

        card.add(info, BorderLayout.CENTER);
        card.add(verBtn, BorderLayout.SOUTH);

        return card;
    }

private void filtrarPorNombre() {
    String texto = txtBuscar.getText().trim();

    panelCatalogo.removeAll();

    CancionDAO dao = new CancionDAO();
    List<cancion> lista = dao.buscarCanciones(texto);

    for (cancion c : lista) {
        panelCatalogo.add(crearCardCancionDB(c));
    }

    panelCatalogo.revalidate();
    panelCatalogo.repaint();
}

private void filtrarPorGenero() {
    int index = comboGenero.getSelectedIndex();

    // 0 = todos
    if (index == 0) {
        cargarCatalogoBD();
        return;
    }

    panelCatalogo.removeAll();

    CancionDAO dao = new CancionDAO();
    List<cancion> lista = dao.buscarPorGenero(index);

    for (cancion c : lista) {
        panelCatalogo.add(crearCardCancionDB(c));
    }

    panelCatalogo.revalidate();
    panelCatalogo.repaint();
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelBase;
    // End of variables declaration//GEN-END:variables
}
