/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.polisong.view;

import com.polisong.controller.RecopilacionController;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Jeferson
 */
public class FormularioEditarRecopilacion extends javax.swing.JDialog {

    private final Recopilaciones ventanaPadre;

    /**
     * Creates new form FormularioEditarRecopilacion
     */
    public FormularioEditarRecopilacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        estilizarCampo(nombre);
        estilizarTextAreaPlano(descripcion);
        personalizarBoton();
        getRootPane().setBorder(new LineBorder(Color.DARK_GRAY, 3, true));
        this.ventanaPadre = (Recopilaciones) parent;
        setLocationRelativeTo(parent);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JTextField();
        BtnEditar = new javax.swing.JButton();
        descripcion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 370, 38));

        BtnEditar.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        BtnEditar.setText("Guardar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 100, 30));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        getContentPane().add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 370, 80));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Descripción");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BtnAtras--1.PNG"))); // NOI18N
        Atras.setBorder(null);
        Atras.setContentAreaFilled(false);
        Atras.setFocusPainted(false);
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FormRecoEdit.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 983, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int idRecopilacion; // guardamos el ID

    public void setDatos(int id, String nombres, String descrip) {
        this.idRecopilacion = id;
        nombre.setText(nombres);
        descripcion.setText(descrip);
    }


    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed

        this.dispose();  // cierra la pantalla actual        // TODO add your handling code here:
    }//GEN-LAST:event_AtrasActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        String nombres = nombre.getText().trim();
        String descrip = descripcion.getText().trim();
        boolean esPublica = false;

        //Validaciones
        if (nombres.isBlank()) {
            ImageIcon raw = new ImageIcon(getClass().getResource("/images/Icono1Info.png"));
            Image imgInfo = raw.getImage().getScaledInstance(90, 90, Image.SCALE_SMOOTH);
            ImageIcon icono = new ImageIcon(imgInfo);

            JOptionPane.showMessageDialog(
                    this,
                    "El nombre no puede estar vacío.",
                    "Aviso",
                    JOptionPane.PLAIN_MESSAGE,
                    icono
            );
            return;
        }

        if (nombres.length() > 100) {
            ImageIcon raw = new ImageIcon(getClass().getResource("/images/Icono1Info.png"));
            Image imgInfo = raw.getImage().getScaledInstance(90, 90, Image.SCALE_SMOOTH);
            ImageIcon icono = new ImageIcon(imgInfo);

            JOptionPane.showMessageDialog(
                    this,
                    "El nombre no puede superar los 100 caracteres.",
                    "Aviso",
                    JOptionPane.PLAIN_MESSAGE,
                    icono
            );
            return;
        }

        if (descrip.isBlank()) {
            ImageIcon raw = new ImageIcon(getClass().getResource("/images/Icono1Info.png"));
            Image imgInfo = raw.getImage().getScaledInstance(90, 90, Image.SCALE_SMOOTH);
            ImageIcon icono = new ImageIcon(imgInfo);

            JOptionPane.showMessageDialog(
                    this,
                    "La descripción no puede estar vacía.",
                    "Aviso",
                    JOptionPane.PLAIN_MESSAGE,
                    icono
            );
            return;
        }

        if (descrip.length() > 255) {
            ImageIcon raw = new ImageIcon(getClass().getResource("/images/Icono1Info.png"));
            Image imgInfo = raw.getImage().getScaledInstance(90, 90, Image.SCALE_SMOOTH);
            ImageIcon icono = new ImageIcon(imgInfo);

            JOptionPane.showMessageDialog(
                    this,
                    "La descripción no puede superar los 255 caracteres.",
                    "Aviso",
                    JOptionPane.PLAIN_MESSAGE,
                    icono
            );
            return;
        }

        RecopilacionController controller = new RecopilacionController();

        boolean actualizado = controller.editarRecopilacion(
                idRecopilacion,
                nombres,
                descrip,
                esPublica
        );

        if (actualizado) {

            ImageIcon raw = new ImageIcon(getClass().getResource("/images/IconoExito1.png"));
            Image imgExito = raw.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            ImageIcon icono = new ImageIcon(imgExito);

            JOptionPane.showMessageDialog(
                    this,
                    "Recopilación editada con éxito.",
                    "Éxito",
                    JOptionPane.PLAIN_MESSAGE,
                    icono
            );

            nombre.setText("");
            descripcion.setText("");

            ventanaPadre.cargarRecopilacionesEnTabla();
            dispose();

        } else {

            ImageIcon raw = new ImageIcon(getClass().getResource("/images/IconoError.png"));
            Image imgError = raw.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            ImageIcon icono = new ImageIcon(imgError);

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo editar la recopilación.",
                    "Error",
                    JOptionPane.PLAIN_MESSAGE,
                    icono
            );
        }
    }//GEN-LAST:event_BtnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioEditarRecopilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioEditarRecopilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioEditarRecopilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioEditarRecopilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioEditarRecopilacion dialog = new FormularioEditarRecopilacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void estilizarCampo(javax.swing.JTextField campo) {
        campo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        campo.setBackground(java.awt.Color.WHITE);
        campo.setForeground(new java.awt.Color(50, 50, 50));

        campo.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1),
                javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10) // padding interno
        ));

        campo.setCaretColor(new java.awt.Color(60, 60, 60));
    }

    private void estilizarTextAreaPlano(javax.swing.JTextArea area) {
        area.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        area.setBackground(java.awt.Color.WHITE);
        area.setForeground(new java.awt.Color(50, 50, 50));

        area.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1),
                javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10)
        ));

        area.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                area.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 140, 255), 1),
                        javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10)
                ));
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                area.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1),
                        javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10)
                ));
            }
        });
    }

    private void personalizarBoton() {

        Color colorNormal = new Color(46, 204, 113);
        Color colorHover = new Color(39, 174, 96);

        BtnEditar.setBackground(colorNormal);
        BtnEditar.setForeground(Color.WHITE);
        BtnEditar.setFont(new java.awt.Font("Bahnschrift", java.awt.Font.BOLD, 14));
        BtnEditar.setOpaque(false);
        BtnEditar.setContentAreaFilled(false);
        BtnEditar.setBorderPainted(false);
        BtnEditar.setFocusPainted(false);
        BtnEditar.setBorder(BorderFactory.createEmptyBorder(8, 20, 8, 20));

        BtnEditar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // Fondo redondeado
                g2.setColor(BtnEditar.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30);

                g2.dispose();
                super.paint(g, c);
            }
        });

        BtnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEditar.setBackground(colorHover);
                BtnEditar.repaint();
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEditar.setBackground(colorNormal);
                BtnEditar.repaint();
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
