/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.polisong.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.UIDefaults;

/**
 *
 * @author Jeferson
 */
public class FormularioRecopilacion extends javax.swing.JDialog {

    /**
     * Creates new form FormularioRecopilacion
     */
    public FormularioRecopilacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        estilizarCampo(jTextField1);
        estilizarTextAreaPlano(jTextArea1);
        personalizarBoton();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 370, 30));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Descripción");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BtnAtras--1.PNG"))); // NOI18N
        Atras.setBorder(null);
        Atras.setContentAreaFilled(false);
        Atras.setFocusPainted(false);
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        btnCrear.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 90, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 370, 70));
        jTextArea1.getAccessibleContext().setAccessibleParent(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FormReco.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 985, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioRecopilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioRecopilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioRecopilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioRecopilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioRecopilacion dialog = new FormularioRecopilacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void estilizarCampo(javax.swing.JTextField campo) {
    campo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    campo.setBackground(java.awt.Color.WHITE);
    campo.setForeground(new java.awt.Color(50, 50, 50));

    // 🔹 Borde gris claro estilo Bootstrap
    campo.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1),
            javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10) // padding interno
    ));

    // 🔹 Quitar borde azul de enfoque
    campo.setCaretColor(new java.awt.Color(60, 60, 60));
}

    private void estilizarTextAreaPlano(javax.swing.JTextArea area) {
    area.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    area.setBackground(java.awt.Color.WHITE);
    area.setForeground(new java.awt.Color(50, 50, 50));

    // 🔹 Borde gris suave estilo Bootstrap
    area.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1),
            javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10)
    ));

    // 🔹 Efecto al enfocar (azul claro)
    area.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            area.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 140, 255), 1),
                    javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10)
            ));
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            area.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1),
                    javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10)
            ));
        }
    });
}
    
    
private void personalizarBoton() {

    // 🔹 Colores
    Color colorNormal = new Color(46, 204, 113);
    Color colorHover  = new Color(39, 174, 96);

    // 🔹 Configuración general del botón
    btnCrear.setBackground(colorNormal);
    btnCrear.setForeground(Color.WHITE);
    btnCrear.setFont(new java.awt.Font("Bahnschrift", java.awt.Font.BOLD, 14));
    btnCrear.setOpaque(false); // importante para redondeado
    btnCrear.setContentAreaFilled(false);
    btnCrear.setBorderPainted(false);
    btnCrear.setFocusPainted(false);
    btnCrear.setBorder(BorderFactory.createEmptyBorder(8, 20, 8, 20));

    // 🔹 UI personalizada para pintar un rectángulo redondeado
    btnCrear.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
        @Override
        public void paint(Graphics g, JComponent c) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            // Fondo redondeado
            g2.setColor(btnCrear.getBackground());
            g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30); // esquinas de 20px

            g2.dispose();
            super.paint(g, c);
        }
    });

    // 🔹 Efecto hover
    btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btnCrear.setBackground(colorHover);
            btnCrear.repaint();
        }
        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnCrear.setBackground(colorNormal);
            btnCrear.repaint();
        }
    });
}







    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
